services:
  caddy:
    restart: "no"
    ports: !override
      - "8080:80"
    environment:
      - BACKEND_DOMAIN=backend
      - FRONTEND_DOMAIN=frontend
      - BACKEND_PORT=8000
      - FRONTEND_PORT=3000
    develop:
      watch:
        - path: ./caddy
          action: rebuild

  db:
    restart: "no"
    ports:
      - "5432:5432"

  redis:
    restart: "no"
    ports:
      - "6379:6379"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    command: ["fastapi", "run", "--reload", "app/main.py"]
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
    build:
      target: dev
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore:
            - ./frontend/.next
            - ./frontend/node_modules
        - path: ./frontend/package-lock.json
          action: rebuild
