services:
  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    restart: "no"
    ports:
      - "127.0.0.1:6379:6379"

  backend:
    restart: "no"
    ports:
      - "127.0.0.1:8000:8000"
    command: ["fastapi", "run", "--reload", "app/main.py"]
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    restart: "no"
    ports:
      - "127.0.0.1:3000:3000"
    build:
      target: dev
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore:
            - ./frontend/.next
            - ./frontend/node_modules
        - path: ./frontend/package-lock.json
          action: rebuild
