[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.1"
hooks = [
  { id = "ruff-check", files = "^backend/", types=["python"] },
  { id = "ruff-format", files = "^backend/", types=["python"] },
]

[[repos]]
repo = "local"
hooks = [
  { 
    id = "local-mypy",
    name = "mypy",
    entry = "uv run --directory backend/app mypy .",
    language = "system",
    files = "^backend/app/.*\\.py$",
    pass_filenames = false,
    require_serial = true,
  },
]