"""Initial migration

Revision ID: 0066a1e59091
Revises: 
Create Date: 2026-01-20 11:54:30.903767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0066a1e59091'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('url_path', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_timestamp', 'api_metrics', ['project_id', 'timestamp'], unique=False)
    op.create_index('idx_project_url_path', 'api_metrics', ['project_id', 'url_path'], unique=False)
    op.create_index('idx_status_timestamp', 'api_metrics', ['response_status_code', 'timestamp'], unique=False)
    op.create_index(op.f('ix_api_metrics_id'), 'api_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_api_metrics_project_id'), 'api_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_metrics_response_status_code'), 'api_metrics', ['response_status_code'], unique=False)
    op.create_index(op.f('ix_api_metrics_timestamp'), 'api_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_api_metrics_url_path'), 'api_metrics', ['url_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_metrics_url_path'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_timestamp'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_response_status_code'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_project_id'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_id'), table_name='api_metrics')
    op.drop_index('idx_status_timestamp', table_name='api_metrics')
    op.drop_index('idx_project_url_path', table_name='api_metrics')
    op.drop_index('idx_project_timestamp', table_name='api_metrics')
    op.drop_table('api_metrics')
    # ### end Alembic commands ###
