"""streamline_metric_indexes

Revision ID: 2cdf1e51fa20
Revises: c2d9a91f74ab
Create Date: 2026-02-22 14:51:03.939572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '2cdf1e51fa20'
down_revision: Union[str, Sequence[str], None] = 'c2d9a91f74ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_project_method'), table_name='metrics')
    op.drop_index(op.f('idx_project_status_code'), table_name='metrics')
    op.drop_index(op.f('idx_project_url_path'), table_name='metrics')
    op.drop_index(op.f('idx_status_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_method'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_project_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_response_status_code'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_url_path'), table_name='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_metrics_url_path'), 'metrics', ['url_path'], unique=False)
    op.create_index(op.f('ix_metrics_response_status_code'), 'metrics', ['response_status_code'], unique=False)
    op.create_index(op.f('ix_metrics_project_id'), 'metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_metrics_method'), 'metrics', ['method'], unique=False)
    op.create_index(op.f('idx_status_timestamp'), 'metrics', ['response_status_code', 'timestamp'], unique=False)
    op.create_index(op.f('idx_project_url_path'), 'metrics', ['project_id', 'url_path'], unique=False)
    op.create_index(op.f('idx_project_status_code'), 'metrics', ['project_id', 'response_status_code'], unique=False)
    op.create_index(op.f('idx_project_method'), 'metrics', ['project_id', 'method'], unique=False)
    # ### end Alembic commands ###
