"""add_cascade_deletes_and_length_constraints

Revision ID: 4cad5c74dd8c
Revises: cc2db778e650
Create Date: 2026-03-17 11:38:15.571196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '4cad5c74dd8c'
down_revision: Union[str, Sequence[str], None] = 'cc2db778e650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_project_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key('api_keys_project_id_fkey', 'api_keys', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('metrics_project_id_fkey'), 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_project_id_fkey', 'metrics', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('metrics', 'url_path',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('metrics', 'user_agent',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrics', 'user_agent',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('metrics', 'url_path',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint('metrics_project_id_fkey', 'metrics', type_='foreignkey')
    op.create_foreign_key('metrics_project_id_fkey', 'metrics', 'projects', ['project_id'], ['id'])
    op.drop_constraint('api_keys_project_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key('api_keys_project_id_fkey', 'api_keys', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
