"""add project-key autogeneration

Revision ID: 61855b6d7550
Revises: f3a9b2c1d8e4
Create Date: 2026-02-19 10:54:02.444580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '61855b6d7550'
down_revision: Union[str, Sequence[str], None] = 'f3a9b2c1d8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'project_key',
               existing_type=sa.VARCHAR(length=104),
               type_=sa.String(length=105),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'project_key',
               existing_type=sa.String(length=105),
               type_=sa.VARCHAR(length=104),
               existing_nullable=False)
    # ### end Alembic commands ###
