"""reduce project name max length to 40

Revision ID: cc2db778e650
Revises: f291d8e75d7d
Create Date: 2026-03-16 13:03:26.152013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = 'cc2db778e650'
down_revision: Union[str, Sequence[str], None] = 'f291d8e75d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('projects', 'project_key',
               existing_type=sa.VARCHAR(length=105),
               type_=sa.String(length=45),
               existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'project_key',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=105),
               existing_nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
