"""add user projects

Revision ID: ef32e74f4050
Revises: 5c3850040348
Create Date: 2026-02-18 01:41:45.646111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = 'ef32e74f4050'
down_revision: Union[str, Sequence[str], None] = '5c3850040348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', 'viewer', name='projectrole'), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_user_projects_created_at'), 'user_projects', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_projects_created_at'), table_name='user_projects')
    op.drop_table('user_projects')
    op.execute("DROP TYPE IF EXISTS projectrole")
    # ### end Alembic commands ###
