"""init

Revision ID: f0cd9eaaacbd
Revises: 
Create Date: 2026-02-15 01:15:24.163473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = 'f0cd9eaaacbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_apikey_hash'), table_name='api_keys')
    op.drop_index(op.f('idx_project_project_key'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_project_project_key'), 'projects', ['project_key'], unique=False)
    op.create_index(op.f('idx_apikey_hash'), 'api_keys', ['key_hash'], unique=False)
    # ### end Alembic commands ###
